// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChGYvlkeVmbRJ8EkVJGY4pDK5jN404KIU',
    appId: '1:84731507514:web:71b0019e10a905cd779603',
    messagingSenderId: '84731507514',
    projectId: 'hypernotes-b42d0',
    authDomain: 'hypernotes-b42d0.firebaseapp.com',
    storageBucket: 'hypernotes-b42d0.firebasestorage.app',
    measurementId: 'G-1VEHFXW6M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoS6SWy8wHeEkmxnbji5c8xPyXOWI_SZA',
    appId: '1:84731507514:android:0676d4c672dd3ad2779603',
    messagingSenderId: '84731507514',
    projectId: 'hypernotes-b42d0',
    storageBucket: 'hypernotes-b42d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOXVgdNYrKIBc7QJ1FqsXa3onPeNndLFA',
    appId: '1:84731507514:ios:85a78e3bc0f95e5e779603',
    messagingSenderId: '84731507514',
    projectId: 'hypernotes-b42d0',
    storageBucket: 'hypernotes-b42d0.firebasestorage.app',
    iosClientId: '84731507514-c6rmt6nofv8rpmlp73mr3ltii8unnuru.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyperNotesFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOXVgdNYrKIBc7QJ1FqsXa3onPeNndLFA',
    appId: '1:84731507514:ios:85a78e3bc0f95e5e779603',
    messagingSenderId: '84731507514',
    projectId: 'hypernotes-b42d0',
    storageBucket: 'hypernotes-b42d0.firebasestorage.app',
    iosClientId: '84731507514-c6rmt6nofv8rpmlp73mr3ltii8unnuru.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyperNotesFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChGYvlkeVmbRJ8EkVJGY4pDK5jN404KIU',
    appId: '1:84731507514:web:b0bd9daa8fc7da7f779603',
    messagingSenderId: '84731507514',
    projectId: 'hypernotes-b42d0',
    authDomain: 'hypernotes-b42d0.firebaseapp.com',
    storageBucket: 'hypernotes-b42d0.firebasestorage.app',
    measurementId: 'G-2Q7Y6KHPCX',
  );
}
